package consts;

public enum CharacterName {
    ALBEDO, ALHAITHAM, ALOY, AMBER, ARATAKI_ITTO,
    ARLECCHINO, BARBARA, BEIDOU, BENNET, CANDACE,
    CHARLOTTE, CHASCA, CHEVREUSE, CHIORI, CHONGYUN,
    CLORINDE, COLLEI, CYNO, DEHYA, DILUC,
    DIONA, DORI, EMILIE, EULA, FARUZAN,
    FISCHL, FREMINET, FURINA, GAMING, GANYU,
    GOROU, HUTAO, JEAN, KACHINA, KAEDEHARA_KAZUHA,
    KAEYA, KAMISATO_AYAKA, KAMISATO_AYATO, KAVEH, KEQING,
    KINICH, KIRARA, KLEE, KUJOU_SARA, KUKI_SHINOBU,
    LAYLA, LISA, LYNETTE, LYNEY, MIKA,
    MONA, MUALANI, NAHIDA, NAVIA, NEUVILLETTE,
    NILOU, NINGGUANG, NOELLE, ORORON, QIQI,
    RAIDEN_SHOGUN, RAZOR, ROSARIA, SANGONOMIYA_KOKOMI, SAYU,
    SETHOS, SHENHE, SHIKANOIN_HEIZOU, SIGEWINNE, SUCROSE,
    TARTAGLIA, THOMA, TIGHNARI, VENTI, WANDERER,
    WRIOTHESLEY, XIANGLING, XIANYUN, XIAO, XILONEN,
    XINGQIU, XINYAN, YAE_MIKO, YANFEI, YAOYAO,
    YELAN, YOIMIYA, YUNJIN, ZHONGLI
}
